trigger:
  - main

pool:
  vmImage: "windows-latest"

variables:
  buildConfiguration: "Release"
  apkOutputPath: "$(Build.ArtifactStagingDirectory)/apk"

steps:
  - task: UseDotNet@2
    inputs:
      packageType: "sdk"
      version: "8.x"
      installationPath: $(Agent.ToolsDirectory)/dotnet

  - script: |
      dotnet workload install maui
    displayName: "Installer les workloads MAUI"

  - task: DotNetCoreCLI@2
    inputs:
      command: "restore"
      projects: "Mds.Maui.Blazor/Mds.Maui.Blazor.csproj"

  - task: DotNetCoreCLI@2
    inputs:
      command: "build"
      projects: "Mds.Maui.Blazor/Mds.Maui.Blazor.csproj"
      arguments: "-f:net8.0-android -c $(buildConfiguration) /p:AndroidPackageFormat=apk /p:OutputPath=$(apkOutputPath)"

  - script: dir "$(apkOutputPath)" /s
    displayName: "📂 Vérifier les fichiers générés"

  - task: PublishBuildArtifacts@1
    displayName: "📢 Publier l'APK"
    inputs:
      PathtoPublish: "$(apkOutputPath)"
      ArtifactName: "apk"
      publishLocation: "Container"
